### ISSUE TITLE
[Bug]: UTF-8 Encoding Issue: Umlauts and Special Characters Not Displayed Correctly

### ISSUE THREAD

**Issue by robertspektor** [benbjurstrom/prezet#66]
### What happened?

There is an issue with the way special characters like umlauts (e.g., “ä”, “ö”, “ü”) and other UTF-8 characters are handled in the GetHeadings class. When parsing HTML content that contains such characters, they are not rendered correctly (e.g., “Verschlüsselung” becomes “VerschlÃ¼sselung”). This happens because the default encoding used by DOMDocument::loadHTML is ISO-8859-1, and UTF-8 is not properly recognized unless explicitly set.

### How to reproduce the bug

	1.	Create a Markdown article with headings that include special characters (e.g., umlauts such as “ä”, “ö”, “ü”).
	2.	Render the page and check the “On this page” section, where the headings are listed.
	3.	Observe that special characters in the headings are not displayed correctly.

### Package Version

0.11.0

### PHP Version

8.3.8

### Laravel Version

11.22.0

### Which operating systems does with happen with?

macOS

### Notes

Here is the proposed code change in the GetHeadings::handle() method:

`
public static function handle(string $html): array
{
    // Ensure UTF-8 encoding is set
    $html = '<?xml encoding="UTF-8">' . $html;

    $dom = new DOMDocument;
    @$dom->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);

    return self::extractHeadings($dom);
}
`

**Comment by robertspektor** [comment]
I also noticed an issue with the way Str::slug handles umlauts (e.g., “ä”, “ö”, “ü”). The current implementation removes these characters from the slug, but I would prefer to keep them in the URL (e.g., “ä” should remain “ä”).

From what I understand, modern browsers and web standards fully support umlauts and other non-ASCII characters in URLs, so I don’t believe it should cause any issues to include them. It would be great if the package could handle this by either modifying or bypassing Str::slug to allow umlauts in URLs.

**Comment by benbjurstrom** [comment]
Thanks for the report and especially for including the code changes. They seemed to do the trick. Regarding `Str::slug` I noticed that by passing null to the language parameter it seems to preserve those characters. So I made that update as well.

**Comment by robertspektor** [comment]
Thanks for the quick fix. I didn’t know about the language parameter either. Cool!
