### ISSUE TITLE
Add optional filename parameter to getNav

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [benbjurstrom/prezet#70]
### What happened?

Currently it does not seem possible to have multiple docs/blogs/languages within a single Prezet installation. 

### How to reproduce the bug

When overwriting the ShowController, wouldn't it be nice to be able to inject the name of the Summary that gets loaded?

So instead of 

`$nav = Prezet::getNav();`

We would get someting like 

`$nav = Prezet::getNav('SUMMARY-LANG.MD');`

I feel that this Summary/Navigation loading based on a variable would easily add a lot of flexibility to the package.

### Package Version

latest

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

### Notes

(I know this isn't a bug, but I could report this in any other manner.)

**Comment by benbjurstrom** [comment]
If I'm understanding correctly the ask is for the getNav method to accept an optional filename parameter making it possible to fetch sidebar content from different summary files. If so I like it.

**Comment by ThisIsMyFavouriteJar** [comment]
Hi Ben, that is exactly what the question was! I think this is very easy to implement, but would have great benefits, also when considering multilanguage etc! Thanks for the package btw, I like it so far!

What I would do in the GetSummary class, change these 2 lines:

`    public static function handle(string $filename = 'SUMMARY.md'): Collection
    {
        $md = Storage::disk(GetPrezetDisk::handle())->get($filename);`

Though I am sure there is another/better way!

**Comment by abeta-io** [comment]
Hi @benbjurstrom , is this the recommended way to deal with multi locale as well? Or will there be another feature for multi locale in the near future?

**Comment by ThisIsMyFavouriteJar** [comment]
Hi @benbjurstrom , is this the recommended way to deal with multi locale as well? Or will there be another feature for multi locale in the near future?

**Comment by benbjurstrom** [comment]
I don't really have anything planned for multi locale but am open to suggestions. But I am curious, when you say multi locale do you mean strings within the blade templates or do you mean the actual markdown content is in different languages?

If the former then I would just wrap Laravel's `__()` function around all the strings in the published blade files. 

If instead you're dealing with markdown content that's duplicated across multiple languages then I would probably override the [Index](https://github.com/benbjurstrom/prezet/blob/main/src/Http/Controllers/IndexController.php)/[Show](https://github.com/benbjurstrom/prezet/blob/main/src/Http/Controllers/ShowController.php) controllers to filter/redirect depending on the chosen locale.

To filter or redirect you could store the language and article identifiers in the front matter as tags. Or extend the FrontmatterData class and add new properties.
