### ISSUE TITLE
[Bug]: Is it Laravel 10 compatible?

### ISSUE THREAD

**Issue by ijpatricio** [benbjurstrom/prezet#71]
### What happened?

Hey Ben! Thanks for this work!

I installed on a fresh new Laravel 11 app for the test drive, and all went smooth, enjoyed it a lot!

But then, I started it on a production app, and it's Laravel 10.

Errors I got after installing, in order:

- Unrecognized Middleware class `ValidateCsrfToken`. L11 has that, L10 has `VerifyCsrfToken`
- On Youtube component `Method Illuminate\View\ComponentAttributeBag::all does not exist.`. In L11, that object has `all` method, not in L10.
  - I removed the MD portion that makes render such component to proceeed.
- Error `Attempt to read property "createdAt" on string` in `resources / views / vendor / prezet / components / article.blade.php`
  - $article is a Json string 
  - could fix with this snippet - added that php sentence to convert string back
  ```blade
                @foreach ($articles as $article)
                    @php
                        $article = new \BenBjurstrom\Prezet\Data\FrontmatterData(json_decode($article, associative: true));
                    @endphp
                    <li class="py-12">
                        <x-prezet::article :article="$article" />
                    </li>
                @endforeach
  ```

### How to reproduce the bug

Install in Laravel 10, I think!

### Package Version

 0.12.0

### PHP Version

8.3.9

### Laravel Version

10.48.22

**Comment by benbjurstrom** [comment]
Thanks for the report. I would like to support Laravel 10 for now. Should have a fix for these issues up later today.

**Comment by ijpatricio** [comment]
Glad I could help ❤️
