### ISSUE TITLE
[Bug]: Image handling mixes fileextensions and formats.

### ISSUE THREAD

**Issue by fuzzyfox** [benbjurstrom/prezet#76]
### What happened?

Currently the image handling route, and the ogimage generator both mismatch file extensions with file types.

### How to reproduce the bug

In [`src/Actions/GenerateOgImage.php`](https://github.com/benbjurstrom/prezet/blob/main/src/Actions/GenerateOgImage.php#L19-L22) Lines 19 and 21, the screenshot is being taken to `webp` format, while the file is saved as `.png`.

In [`src/Http/Controllers/ImageController.php`](https://github.com/benbjurstrom/prezet/blob/main/src/Http/Controllers/ImageController.php#L16) despite the `GetImage` action handling the files in their own format, the response is forced to use the `image/webp` header, rather than the correct mime-type for the image being requested.

### Package Version

0.14.0

### PHP Version

8.3.11

### Laravel Version

11.23.5

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

For the image generator this is a fairly straight-fwd solution of changing the output file type.

For the image endpoint my proposal is to do one of two actions, with a personal preference to option 1.

1. Simply fix the returned content-type based on the image data being served.
2. Refactor the `GetImage` action to always return `webp` and ignore the file extension. (Ideally with a redirect to `.webp` at the end of the URL so the image mime and extension match in the URL

I intend to open a PR with a solution for the issue(s) shortly, using option 1 as the approach for the image requests.

**Comment by benbjurstrom** [comment]
Good catch, I've been using webp exclusively so didn't notice. I'm fine with 1. 

The GetImage action already validates the given file extension to one of webp, png, or jpg so it's probably safe to just do something like this:

```php
<?php

namespace BenBjurstrom\Prezet\Http\Controllers;

use BenBjurstrom\Prezet\Actions\GetImage;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ImageController
{
    public function __invoke(Request $request, string $path): Response
    {
        $file = GetImage::handle($path);
        $ext = pathinfo($path, PATHINFO_EXTENSION);

        return response($file, 200, [
            'Content-Type' => 'image/' . $ext,
            'Cache-Control' => 'public, max-age=31536000',
        ]);
    }
}


```

**Comment by fuzzyfox** [comment]
I ended up using a [`match` statement](https://github.com/benbjurstrom/prezet/pull/77/files#diff-9d736a053b8ad3ff6b249834b84a0e415cc0f2c97470db0bc539a74fb653f004R16) as the mime for JPEG is `image/jpeg` not `image/jpg`. I also allowed for the `.jpeg` extension should someone want to use that in future.

**Comment by fuzzyfox** [comment]
#77 applies fixes discussed.
