### ISSUE TITLE
[Bug]: prezet:index throws error for SQLSTATE 11 database disk image

### ISSUE THREAD

**Issue by skino2019** [benbjurstrom/prezet#78]
### What happened?

I cannot load the site now as im getting an SQLSTATE error:

  `SQLSTATE[HY000]: General error: 11 database disk image is malformed (Connection: prezet, SQL: select name from sqlite_master where type = 'table' and name not like 'sqlite_%' order by name)
`

### How to reproduce the bug

Unfortunately i have no idea how to reproduce this, i was rebuilding the front end to use a different theme and everything was working. i got to a point where the app was working still and decided to leaver it for the night. this morning i tried again and its now giving me the error message:

  `SQLSTATE[HY000]: General error: 11 database disk image is malformed (Connection: prezet, SQL: select name from sqlite_master where type = 'table' and name not like 'sqlite_%' order by name)`

### Package Version

0.14.0

### PHP Version

8.2

### Laravel Version

11

### Notes

Ive never used SQLite before and always used MySQL and postgres so appologies if this is something obvious.

**Comment by benbjurstrom** [comment]
I've been hitting this too lately, not exactly sure why but the fix is simple. Make sure you're on the latest version (0.14.0), delete your prezet.sqlite file, recreate it, and reindex.

```bash
rm prezet.sqlite && touch prezet.sqlite && php artisan prezet:index
```

**Comment by benbjurstrom** [comment]
Just pushed v0.15.0 which hopefully prevents it from happening again.
