### ISSUE TITLE
[Bug]: Errors adding youtube links

### ISSUE THREAD

**Issue by skino2019** [benbjurstrom/prezet#81]
### What happened?

When I add a YouTube video to my md file, I get the following error.

  The upload date field is required. (View: C:\laragon\www\fatty\resources\views\vendor\prezet\components\youtube.blade.php) (View: C:\laragon\www\fatty\resources\views\vendor\prezet\components\youtube.blade.php)

### How to reproduce the bug

When i add this 

``` html +parse
<x-prezet::youtube videoid="w2jsKXRdC2M" title="Bryn Eurin Test Flight">
    Login
</x-prezet::youtube>
```

I get the error message:

  The upload date field is required. (View: C:\laragon\www\fatty\resources\views\vendor\prezet\components\youtube.blade.php) (View: C:\laragon\www\fatty\resources\views\vendor\prezet\components\youtube.blade.php)

The full URL to the YT video is 

https://www.youtube.com/watch?v=w2jsKXRdC2M

### Package Version

0.14.0

### PHP Version

8.2

### Laravel Version

11

### Notes

Just as a note i am including the 3 ` in the message above but its just showing without :P

**Comment by skino2019** [comment]
Just as a note i am including the 3 **`** in the message above but  its just showing without :P

**Comment by benbjurstrom** [comment]
As the error suggest upload date is a required prop. It also allows for an alias of date. You can pass it into the component like this:

```html
<x-prezet::youtube videoid="w2jsKXRdC2M" title="Bryn Eurin Test Flight" date="2023-07-26T12:00:00+00:00">
    Login
</x-prezet::youtube>
```

**Comment by skino2019** [comment]
My error, i assumed the date was pulled from the Youtube link itself.

might be worth adding that to the documentation as it doesnt mention the date on the blade components section.
