### ISSUE TITLE
[Bug]: prezet:index Malformed DB 

### ISSUE THREAD

**Issue by skino2019** [benbjurstrom/prezet#82]
### What happened?

Im unable to do the php artisan prezet:index when i run the command i get this 

```
$ php artisan prezet:index

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 11 database disk image is malformed (Connection: prezet, SQL: select name from sqlite_master where type = 'table' and name not like 'sqlite_%' order by name)
```

### How to reproduce the bug

Not sure how or where it starts but one minute i can do the php artisan prezet:index and the next i get the following error

```
$ php artisan prezet:index

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 11 database disk image is malformed (Connection: prezet, SQL: select name from sqlite_master where type = 'table' and name not like 'sqlite_%' order by name)
```

i have worked through your mentioned fix [Here](https://github.com/benbjurstrom/prezet/issues/78) but its still not working.

### Package Version

0.15.0

### PHP Version

8.2

### Laravel Version

11

### Notes

PS I love this project a lot. it will make managing my blog so much easier going forward just need to get it working and looking how i need it :D

**Comment by benbjurstrom** [comment]
Hmm, this came up in #78. I thought I fixed it in v0.15.0 but if you're on that version and still seeing it I'll have to look into it more.

Thankfully it can be temporarily fixed fairly easy. Just delete your prezet.sqlite file, recreate it, and reindex. You can use this one liner from the root of the project.

```bash
rm prezet.sqlite && touch prezet.sqlite && php artisan prezet:index
```

**Comment by skino2019** [comment]
this 

`rm prezet.sqlite && touch prezet.sqlite && php artisan prezet:index`
isnt working

**Comment by benbjurstrom** [comment]
Oh sorry, didn't see you had already tried that. In the root of your laravel application you should have a file called prezet.sqlite. Delete it. Then create a new file in that spot with the same name.

**Comment by skino2019** [comment]
That resolved it. Thank you
